version: '3'
services:
  db-development:
    image: mysql:8.0.14
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3316:3306"
    volumes:
      - ./docker/mysql_development/volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cryptocoin
      MYSQL_PASSWORD: cryptocoin
      MYSQL_DATABASE: cryptocoin_development
  db-test:
    image: mysql:8.0.14
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "4316:4306"
    volumes:
      - ./docker/mysql_test/volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: cryptocoin
      MYSQL_PASSWORD: cryptocoin
      MYSQL_DATABASE: cryptocoin_test
  redis-development:
    image: redis:alpine
    ports:
      - '16379:6379'
    volumes:
      - ./docker/redis_data_development:/data
  redis-test:
    image: redis:alpine
    ports:
      - '26379:6379'
    volumes:
      - ./docker/redis_data_test:/data
