production:
  :schedule:
    # notify_shooting_up_down:
    #   every: 10s
    #   class: NotifyShootingUpDownWorker
    notify_shooting_up_down_btc_usd:
      every: 10s
      class: NotifyShootingUpDownBtcUsdWorker
    notify_best_arbitrage_btc:
      every: 30s
      class: NotifyBestArbitrageBtcWorker
    # order_btc:
    #   every: 10s
    #   class: OrderBtcWorker
    # mex_maker_bot:
    #   every: 60s
    #   class: MexMakerBotWorker
    mex_maker_buy_bot:
      every: 120s
      class: MexMakerBuyBotWorker
    mex_maker_sell_bot:
      every: 120s
      class: MexMakerSellBotWorker
    collect_count:
      cron: '0 5 0 * * *'
      class: CollectCountWorker
development:
  :schedule:
    # notify_shooting_up_down_btc_usd:
    #   every: 10s
    #   class: NotifyShootingUpDownBtcUsdWorker
    # mex_maker_bot:
    #   every: 5s
    #   class: MexMakerBotWorker
    mex_maker_buy_bot:
      every: 120s
      class: MexMakerBuyBotWorker
    mex_maker_sell_bot:
      every: 120s
      class: MexMakerSellBotWorker
    # mex_predict_price:
    #   every: 1800s
    #   class: MexPredictPriceWorker
:logfile: ./log/sidekiq.log
:concurrency: 1
