:schedule:
  notify_shooting_up_down:
    every: 5s
    class: NotifyShootingUpDownWorker
  notify_best_arbitrage_btc:
    every: 20s
    class: NotifyBestArbitrageBtcWorker
  order_btc:
    every: 10s
    class: OrderBtcWorker
:logfile: ./log/sidekiq.log
:concurrency: 5
