production:
  :schedule:
    notify_shooting_up_down:
      every: 10s
      class: NotifyShootingUpDownWorker
    notify_shooting_up_down_btc_usd:
      every: 10s
      class: NotifyShootingUpDownBtcUsdWorker
    notify_best_arbitrage_btc:
      every: 30s
      class: NotifyBestArbitrageBtcWorker
    order_btc:
      every: 10s
      class: OrderBtcWorker
    # order_btc2:
    #   every: 10s
    #   class: OrderBtcWorker2
    mex_maker_bot:
      every: 60s
      class: MexMakerBotWorker
    collect_count:
      cron: '0 5 0 * * *'
      class: CollectCountWorker
:logfile: ./log/sidekiq.log
:concurrency: 5
